<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>App_Plugins/punkTwoFactor</StaticWebAssetBasePath>
		<Version>18.0.0</Version>
		<Product>punkTwoFactor</Product>
		<PackageId>punkTwoFactor</PackageId>
		<Title>punkTwoFactor</Title>
		<Description>An app_plugin for Umbraco that sets up Two Factor Authentication.</Description>
		<PackageTags>umbraco;umbraco-marketplace;2fa;two-factor-authentication</PackageTags>
		<RootNamespace>punkTwoFactor</RootNamespace>
		<Authors>Gareth Wright</Authors>
		<PackageProjectUrl>https://github.com/garpunkal/punkTwoFactor</PackageProjectUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/garpunkal/punkTwoFactor</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
		<PackageReference Include="Umbraco.Cms.Core" Version="18.2.1" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="18.2.1" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="18.2.1" />
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="18.2.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\LICENSE" Pack="true" PackagePath="" />
		<None Include="..\logo.png" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>  
